# Generated by Django 3.2.13 on 2022-11-02 09:34

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/')),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('관광지', '관광지'), ('음식점', '음식점'), ('숙소', '숙소')], default='관광지', max_length=10)),
            ],
        ),
    ]
