# Generated by Django 3.2.13 on 2022-11-04 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='이름')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/', verbose_name='대표이미지')),
                ('country', models.CharField(max_length=80, verbose_name='국가')),
                ('city', models.CharField(max_length=80, verbose_name='도시')),
                ('category', models.CharField(choices=[('관광지', '관광지'), ('음식점', '음식점'), ('숙소', '숙소')], default='관광지', max_length=10, verbose_name='카테고리')),
                ('lat', models.CharField(max_length=80, verbose_name='위도')),
                ('lng', models.CharField(max_length=80, verbose_name='경도')),
                ('desc', models.TextField(blank=True, max_length=300, verbose_name='장소 설명문')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
