# Generated by Django 3.2.13 on 2022-11-01 01:29

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/')),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('grade', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='평점')),
                ('category', models.CharField(choices=[('tour', '관광지'), ('restaurant', '음식점'), ('hotel', '숙소')], default='관광지', max_length=10)),
            ],
        ),
    ]
