# Generated by Django 3.2.13 on 2022-11-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='grade',
        ),
    ]
