# Generated by Django 3.2.13 on 2022-11-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('tour', '관광지'), ('restaurant', '음식점'), ('hotel', '숙소')], default='tour', max_length=10),
        ),
    ]
