# Generated by Django 3.2.13 on 2022-11-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_location_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=80, verbose_name='이름'),
        ),
    ]
