# Generated by Django 3.2.13 on 2022-11-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_location_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('관광지', '관광지'), ('음식점', '음식점'), ('숙소', '숙소')], default='관광지', max_length=10),
        ),
    ]
