# Generated by Django 3.2.13 on 2022-11-04 10:32

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_location_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('관광지', '관광지'), ('음식점', '음식점'), ('숙소', '숙소')], default='관광지', max_length=10, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=80, verbose_name='도시'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=80, verbose_name='국가'),
        ),
        migrations.AlterField(
            model_name='location',
            name='desc',
            field=models.TextField(blank=True, max_length=300, verbose_name='장소 설명문'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/', verbose_name='대표이미지'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.CharField(max_length=80, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.CharField(max_length=80, verbose_name='경도'),
        ),
    ]
