# Generated by Django 3.2.13 on 2022-11-01 14:56

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_location_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/'),
        ),
    ]
