# Generated by Django 3.2.13 on 2022-11-04 15:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='평점')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/')),
                ('traveled_at', models.CharField(choices=[('2022-11', '2022년 11월'), ('2022-10', '2022년 10월'), ('2022-09', '2022년 09월'), ('2022-08', '2022년 08월'), ('2022-07', '2022년 07월'), ('2022-06', '2022년 06월'), ('2022-05', '2022년 05월'), ('2022-04', '2022년 04월'), ('2022-03', '2022년 03월'), ('2022-02', '2022년 02월'), ('2022-01', '2022년 01월'), ('2021-12', '2021년 12월')], default='2022년 11월', max_length=12)),
                ('companion', models.CharField(choices=[('커플', '커플'), ('가족', '가족'), ('친구', '친구'), ('비즈니스', '비즈니스'), ('솔로', '솔로')], default='가족', max_length=6)),
                ('like_users', models.ManyToManyField(related_name='like_reviews', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
