# Generated by Django 3.2.13 on 2022-11-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='companion',
            field=models.CharField(choices=[('커플', '커플'), ('가족', '가족'), ('친구', '친구'), ('비즈니스', '비즈니스'), ('솔로', '솔로')], default='가족', max_length=6),
        ),
    ]
