# Generated by Django 3.2.13 on 2022-11-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_location_category'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='traveled_at',
            field=models.CharField(choices=[('2022-11', '2022년 11월'), ('2022-10', '2022년 10월'), ('2022-09', '2022년 09월'), ('2022-08', '2022년 08월'), ('2022-07', '2022년 07월'), ('2022-06', '2022년 06월'), ('2022-05', '2022년 05월'), ('2022-04', '2022년 04월'), ('2022-03', '2022년 03월'), ('2022-02', '2022년 02월'), ('2022-01', '2022년 01월'), ('2021-12', '2021년 12월')], default='2022년 11월', max_length=12),
        ),
    ]
